[package]
name = "admin-panel-domain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
sdlc-shared = { path = "../../../services-base/crates/sdlc-shared", default-features = false, features = ["openapi"] }
utoipa = { version = "5", features = ["uuid", "chrono"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
